version: "3.8"

services:
  web:
    image: nginx:1.22
    ports:
      - "127.0.0.1:8080:80"   # <-- localhost-only binding (gÃ¼venli)
    volumes:
      - ./web-content:/usr/share/nginx/html:ro

  client:
    image: alpine
    entrypoint: ["/bin/sh","-c","sleep infinity"]
    networks:
      - synlab_net

networks:
  synlab_net:
    driver: bridge
