version: "3.8"
services:
  web:
    image: nginx:1.22
    ports:
      - "8080:80"
    volumes:
      - ./web-content:/usr/share/nginx/html:ro
  client:
    image: alpine
    entrypoint: ["/bin/sh","-c","sleep infinity"]
